export const PERSONAS = {
  random: {
    id: "random",
    name: "전체 비교",
    description: "구매한 페르소나를 동일 종목에 동시 실행해 한 화면에서 성과를 비교합니다.",
    color: "#06B6D4",
    icon: "Layers",
    price: null,
    risk_level: 3,
    traits: ["동시 비교", "멀티 전략", "무료"],
    best_for: "여러 전략의 성과를 같은 종목으로 직접 비교하고 싶을 때",
    worst_for: "페르소나를 아직 구매하지 않은 경우",
    strategy_steps: [
      "구매 완료된 페르소나를 자동으로 수집",
      "동일한 종목·기간·시작 자본으로 각 페르소나를 동시 실행",
      "수익률 곡선을 한 차트에 겹쳐서 비교",
      "지표 카드(수익률·MDD·승률·거래 횟수)를 나란히 표시",
    ],
    detail_note: "구매한 페르소나가 많을수록 더 풍부한 비교가 가능합니다. 페르소나가 없으면 먼저 하나 이상 구매해주세요.",
  },
  coward: {
    id: "coward",
    name: "신중함",
    description: "이동평균이 상승 중이고 가격이 안정적일 때만 진입. 손익 ±2%에서 정리.",
    color: "#3B82F6",
    icon: "ShieldAlert",
    price: 2,
    risk_level: 1,
    traits: ["저위험", "보수적", "이동평균"],
    best_for: "안정적인 상승장, 변동성이 낮은 시장",
    worst_for: "급등락이 잦은 고변동성 장, 횡보장",
    strategy_steps: [
      "20일 이동평균선이 우상향 중인지 확인",
      "현재가가 이동평균 대비 ±0.5% 이내로 안정적인지 체크",
      "조건 충족 시 자본의 20% 매수 진입",
      "진입가 대비 +2% 도달 시 익절",
      "진입가 대비 -2% 도달 시 손절",
    ],
    detail_note: "수익은 작지만 손실도 최소화하는 '안전제일' 전략입니다. 승률이 중요하고, 손실을 절대 크게 내기 싫은 투자자에게 적합합니다.",
  },
  beast: {
    id: "beast",
    name: "개미",
    description: "직전 3시간 상승 모멘텀 감지 시 자본 80% 매수. 1시간 -0.3% 하락 시 즉시 정리.",
    color: "#10B981",
    icon: "Users",
    price: 2,
    risk_level: 5,
    traits: ["고위험", "모멘텀", "단기매매"],
    best_for: "강한 상승 추세가 있는 모멘텀 장",
    worst_for: "횡보장, 급락 후 반등이 없는 하락장",
    strategy_steps: [
      "직전 3시간 동안 주가가 지속 상승했는지 모멘텀 체크",
      "모멘텀 감지 시 가용 자본의 80%로 공격적 매수",
      "포지션 보유 중 1시간 내 -0.3% 하락 시 즉시 전량 손절",
      "강한 상승세 지속 시 자연스러운 익절",
    ],
    detail_note: "시장 흐름을 그대로 따라가는 수동적인 전략입니다. 상승 모멘텀이 보이면 따라 사고, 흔들리면 바로 나옵니다. 능동적으로 판단하기보다 상승장을 수동적으로 따라가고 싶은 분께 추천합니다.",
  },
  contrarian: {
    id: "contrarian",
    name: "야수의 심장",
    description: "직전 1시간 -1% 이상 급락 시 반등 기대 매수. 진입가 대비 ±1%에서 정리.",
    color: "#EF4444",
    icon: "Flame",
    price: 2,
    risk_level: 3,
    traits: ["역발상", "단기반등", "평균회귀"],
    best_for: "과매도 후 빠른 반등이 있는 시장",
    worst_for: "추세 하락이 지속되는 약세장",
    strategy_steps: [
      "직전 1시간 동안 주가가 -1% 이상 급락했는지 확인",
      "과매도로 인한 반등 기대 매수 진입",
      "진입가 대비 +1% 반등 시 익절",
      "진입가 대비 -1% 추가 하락 시 손절",
    ],
    detail_note: "\"모두가 팔 때 사라\"는 역발상 전략입니다. 단기 반등 포착에 특화되어 있으며, 시장이 너무 빠르게 하락할 때 기회를 노립니다.",
  },
  ai: {
    id: "ai",
    name: "초보 예언가",
    description: "RSI·MACD·볼린저밴드 등 6개 기술지표를 LSTM에 입력해 상승 확률 예측. 확신 없을 땐 즉시 매도, 최대 48봉 보유.",
    color: "#8B5CF6",
    icon: "Cpu",
    price: 2,
    risk_level: 2,
    traits: ["LSTM", "확률기반", "AI"],
    best_for: "패턴이 반복되는 예측 가능한 시장",
    worst_for: "블랙스완 이벤트, 뉴스 충격으로 패턴이 깨지는 시장",
    strategy_steps: [
      "최근 60봉 데이터로 RSI·MACD·볼린저밴드 등 6개 기술 지표 계산",
      "계산된 피처의 마지막 24봉을 LSTM 모델에 입력, 다음 봉 상승 확률 p 예측",
      "확률 p > 0.55 이면 자본의 50% 매수 진입",
      "진입 후 1봉 이상 보유 시 확률 < 0.44 이면 즉시 매도",
      "48봉(약 2거래일) 초과 보유 시 확률 무관 강제 매도",
    ],
    detail_note: "RSI·MACD·볼린저밴드를 포함한 6개 피처를 학습한 LSTM 모델이 매매 신호를 생성합니다. p > 0.52일 때만 매수해 무분별한 진입을 줄이고, 확신이 낮아지면 즉시 청산합니다. 과거 데이터 패턴에 의존하므로 급격한 시장 변화에는 약할 수 있습니다.",
  },
};

export const PERSONA_ORDER = ["coward", "beast", "contrarian", "ai"];
export const FREE_PERSONA = "random";
export const PAID_PERSONAS = PERSONA_ORDER;
